# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Magnetic LLC.
email: orlandovillasenor@me.com
description: > # this means to ignore newlines until "baseurl:"
  We are web developers who are commited to our clients.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://web-magnetic.com" # the base hostname & protocol for your site
twitter_username: devmagnetic
github_username:  orlandovillasenor

# Build settings
markdown: kramdown
